WIP - Daily window smoothed threshold + anomaly score
equinor/gordo pull request #990
Opened 2020-05-18 13:36 UTC by HugoBettMach

Adds the smoothed threshold and anomaly calculation as discussed with the SMEs. In summary:
* keep the current threshold as it is, at least until we decide to officially adopt the method below
* define a time window that should for now be defaulted to 1 day: 144 time steps @ 10T resolution
* calculate another threshold using the same logic here but with that window: `scaled_mse.rolling(144).min().max()`
* make sure another that threshold is set to the third fold like the current one here
* also calculate the feature_thresholds using the same method
* add the new thresholds to the metadata. keep the current ones in there for now
* calculate a scaled and unscaled version of the smoothed total_anomaly using the same rolling window and the median, e.g. `data["smooth-total-anomaly-scaled"] = data["total-anomaly-scaled"].rolling(144).median()`. Do the same for tag-level anomalies.
* recalculate anomaly confidence with the new threshold and the new total_anomaly, also for the tag-level anomaly confidence.

2020-05-21 10:53 UTC, hjarraya approved these changes
LGTM

2020-05-21 10:54 UTC, hjarraya commented
Please run black formatting to fix the build.

2020-05-21 10:54 UTC, hjarraya requested changes
LGTM, fix build, run black formatting.

2020-05-21 14:45 UTC, koropets requested changes
Looks good, but there is still some failed test [here](https://github.com/equinor/gordo/pull/990/checks?check_run_id=700141362)

2020-06-02 10:06 UTC, hjarraya approved these changes
LGTM

2020-06-02 14:04 UTC, merged